In [1]:
import numpy as np

### Create an array of zeros


In [29]:
a=np.zeros((2,3))

In [30]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

### Create an array of ones

In [34]:
b=np.ones((3,4,5),dtype=np.int16)

In [35]:
b

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

### Create an array of evenly spaced values(number of samples)

In [42]:
c= np.linspace(0,2,9) 

In [43]:
c

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Create an array of evenly spaced values(step value)

In [44]:
d = np.arange(5,50,5)

In [45]:
d

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

### Create a 2X2 identity matrix


In [48]:
e= np.eye(3)

In [49]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create an array with random values


In [50]:
 np.random.random((3,3)) 

array([[0.76653104, 0.98063132, 0.13893825],
       [0.35627429, 0.47993168, 0.77039466],
       [0.10118779, 0.37594631, 0.90126662]])

### Create an empty array

In [51]:
 np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])